import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { animated, useSpring } from "@react-spring/web";
import { useEffect } from "react";
import Link from "next/link";
import Intro from "@/components/intro";
import About from "@/components/about";
import Work from "@/components/work";
import Project from "@/components/project";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Fira+Mono&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header>
        <nav>
          <div className="navbar">
            <div className="">
              <Link href="#resume">Logo</Link>
            </div>
            <ol className="navlist">
              <li>About</li>
              <li>Work</li>
              <li>Contact</li>
            </ol>
            <div className="">
              <Link href="#resume">Resume</Link>
            </div>
          </div>
        </nav>
      </header>
      <div className="sidebar"></div>
      <div className="sidebar">
        <ul>
          <li>
            <Link href="https://github.com/ShiuanDinq">
              <img className="icon" src="./github.svg"></img>
            </Link>
          </li>
          <li>
            <Link href="https://www.linkedin.com/in/edmund-shiuan-dinq-hang-264344192/">
              <img className="icon" src="./linkedin.svg"></img>
            </Link>
          </li>
        </ul>
      </div>
      <div className="content">
        <main>
          <Intro />
          <About />
          <Work />
          <Project />
        </main>
      </div>
    </>
  );
}
